/* THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY */

#ifndef FACTORY_HPP
#define FACTORY_HPP

#include "Preprocessor.hpp"
#include "Detector.hpp"
#include "Classifier.hpp"
#include "Config.hpp"

enum ProcessorType {
	CYCLIST_TRACKER = 1,
	DUMMY = 0,
};

/**
 * @brief This class is autogenerated by build/makeFactory.py utility.
 * it is a module factory for each component on modules folder
 */ 
class Factory {
    private:
            Conf *configuration;
            int processorId;
            ProcessorType processorType;
    public:
            Factory(int , Conf &cfg);

            /**
             * @brief Converts string name to enum element
             */
            static ProcessorType getProcessorType(std::string);            
            
            /**
             * @brief Creates new processor instance according to
             * ProcessorType set on class constructor
             */
            Preprocessor *createPreprocessor();
            
            /**
             * @brief Creates new classifier instance according to
             * ProcessorType set on class constructor
             */
            Classifier *createClassifier();
            
            /**
             * @brief Creates new detector instance according to
             * ProcessorType set on class constructor
             */
            Detector *createDetector();
};

#endif
    